### ISSUE TITLE
Maven bundle release

### ISSUE THREAD

**Issue by msmock** [project-husky/husky#28]
For the Impfmodul we require a maven release package we can download form one of the maven repositories online.

**Comment by msmock** [comment]
This is a high priority since i failed to get the husky project running without problems trying IntelliJ or eclipse.

**Comment by ralych** [comment]
We have to define a maven repo to be abel to download.

Workaround: In meantime the build has to be done by maven and command line locally. This helps.

**Comment by qligier** [comment]
Maven central repository is our best option for releases (but it doesn't accept snapshots, as discussed). We could change the namespace and get the associated domain to use it (by example 'org.projecthusky').
Otherwise, we can try to contact the owner of husky.org (the whois is redacted) or wait until it expires (2023/01/13).

**Comment by ralych** [comment]
et-innovation is setting up an maven repository for us. so we can manage snapshots and releases.
the central repository is not yet from the table, but anyway a snapshot repo has to be available too.

**Comment by project-husky-owner** [comment]
is done by release 2.0.0
