### ISSUE TITLE
CH-EMED-EPR: show only narrative when dose or frequency missing in PMLC generator

### ISSUE THREAD

**Issue by qligier** [project-husky/husky#58]
See https://github.com/ahdis/ch-emed-pmp/issues/48

**Comment by dvribeira** [comment]
As a matter of fact, having a look at the issue and the code, isn't it the case already?
The HTML template uses either the 4 columns display for dosage if `dosage.hasIntakes()` is true or `dosage.narrative()` otherwise.
Having a look at the EffectiveDosageInstructions class, it seems to me that:

- hasIntakes() is true only when for a dosage we have both _quantity/rate_ and _when_, hence if either is missing, dosage.narrative() is used.
- dosage.narrative() is simply the text field of the base dosage.

@qligier Could it be that I am simply misunderstanding the issue itself?

**Comment by qligier** [comment]
The issue lies in 

> hence if either is missing, dosage.narrative() is used

dosage.narrative is used, but only for the missing one(s). If both are missing, the resulting medication card is fine. But if only one is missing, then you currently lose information:

- If `quantity/rate` is missing: you know `when` (=> in which column to put the `quantity/rate`), but the `quantity/rate` is lost in the narrative. You need to show the narrative AND to generate a short narrative for the `when`.
- If `when` is missing: you know the quantity, but can't put it in a column. Same thing, you need to show the narrative AND generate a short narrative for the quantity.

**Comment by dvribeira** [comment]
OK, so combining that with https://github.com/hl7ch/ch-emed/issues/215 and the info in https://build.fhir.org/ig/hl7ch/ch-emed//dosage.html and https://build.fhir.org/ig/CARA-ch/ch-emed-epr/StructureDefinition-ch-emed-epr-dosage.html:

- Both `quantity/rate` and `when` are missing: we fill a single cell and row with baseDosage.patientInstruction
- Only `quantity/rate` is missing: we have one row split into the 4 columns for the `when` and another one containing patientInstruction
- Only `when` is missing: we have one row spanning 4 cols with the `quantity/rate` and another row with the baseDosage.patientInstruction
- Nothing is missing: we don't use either baseDosage.text or baseDosage.patientInstruction

However, concerning the _commentaire_ column, at the moment it's filled with baseDosage.patientInstruction but if we are going to use it for the dosage columns, then I wonder if we would have to change the filling to this column to either:
- In any case: we use the contents of baseDosage.additionalInstruction to fill the _commentaire_ column.
- If we have both `quantity/rate` and `when`, use `baseDosage.patientInstruction`, otherwise `baseDosage.additionalInstruction`?
And if using `additionalInstruction` should we just use the `additionalInstruction.text` field?

**Comment by qligier** [comment]
The column _commentaires_ shall always contain the `patientInstruction` and `additionalInstruction.text`, if any. It can always contain non-structured information, even if the important fields are given as structured data.

**Comment by dvribeira** [comment]
After discussion with S. Spahni, we think the best course of action is to display the content as follows:

- We have `quantity/rate` + `when`: as it is now, we split in _when_ cells and fill the quantity/rate. _Commentaire_ contains `patientInstruction` + `treatmentReason`.
- We miss `quantity/rate` but we have `when`: we split in _when_ cells and fill it with a word/expression to state that intake is due. _Commentaire_ contains `patientInstruction` + `treatmentReason`.
- We have `quantity/rate` but we miss `when`: we display the quantity/rate spanning the 4 dosage columns. _Commentaire_ contains `patientInstruction` + `treatmentReason`.
- We miss both `quantity/rate` and `when`: we display `patientInstruction `spanning the 4 dosage columns. _Commentaire_ contains only `treatmentReason`.
